local library = loadstring(game:HttpGet("https://pastebin.com/raw/AtQAJECZ", true))()
local w = library:CreateWindow('Teleports')
w:Section('Top')

local b1 = w:Button("Ground Unit ON", function()
_G.on = true
while _G.on and wait() do pcall(function()
for i,v in pairs(game.Workspace.Units:GetDescendants()) do
    if v:FindFirstChild("HumanoidRootPart") and v.Name ~= "Aerial Noob" then
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Create Projectile",
    [2] = v.HumanoidRootPart.Position
}

game:GetService("Players").LocalPlayer.Character:FindFirstChild("Rocket Launcher").Resources.Gun:FireServer(unpack(args))
end
end
end)
end
end)

local aaaf = w:Button("Ground UNIT OFF", function()
_G.on = false
while _G.on and wait() do pcall(function()
for i,v in pairs(game.Workspace.Units:GetDescendants()) do
    if v:FindFirstChild("HumanoidRootPart") and v.Name ~= "Aerial Noob" then
-- Script generated by SimpleSpy - credits to exx#9394

local args = {
    [1] = "Create Projectile",
    [2] = v.HumanoidRootPart.Position
}

game:GetService("Players").LocalPlayer.Character:FindFirstChild("Rocket Launcher").Resources.Gun:FireServer(unpack(args))
end
end
end)
end
end)
w:Section("Ok")

local faf = w:Button("ALL ON", function()
_G.fafa = true
while _G.fafa and wait() do pcall(function()
for i,v in pairs(game.Workspace.Units:GetChildren()) do
    if v:FindFirstChild("HumanoidRootPart") then

local args = {
    [1] = "Create Projectile",
    [2] = v.HumanoidRootPart.Position
}

game:GetService("Players").LocalPlayer.Character:FindFirstChild("Rocket Launcher").Resources.Gun:FireServer(unpack(args))
end
end
end)
end
end)
local wwhwhwh = w:Button("ALL OFF", function()
_G.fafa = false
while _G.fafa and wait() do pcall(function()
for i,v in pairs(game.Workspace.Units:GetDescendants()) do
    if v:FindFirstChild("HumanoidRootPart") then

local args = {
    [1] = "Create Projectile",
    [2] = v.HumanoidRootPart.Position
}

game:GetService("Players").LocalPlayer.Character:FindFirstChild("Rocket Launcher").Resources.Gun:FireServer(unpack(args))
end
end
end)
end
end)




w:Section("aaa")

local g44g = w:Button("AERIAL TELEPOT ON", function()
_G.bon = true
while _G.bon and wait() do 
for i,v in pairs(game.Workspace.Units:GetChildren()) do
    if string.find(v.Name, "Aerial") and v:FindFirstChild("HumanoidRootPart") then

game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = v.HumanoidRootPart.CFrame
end
end
end
end)

local gwggwgw = w:Button("TELEPOT OFF", function()
_G.bon = false
while _G.bon and wait() do 
for i,v in pairs(game.Workspace.Units:GetChildren()) do
    if string.find(v.Name, "Aerial") and v:FindFirstChild("HumanoidRootPart") then

game:GetService("Players").LocalPlayer.Character.HumanoidRootPart.CFrame = v.HumanoidRootPart.CFrame
end
end
end
end)
